name: 功能需求
description: 给项目提供建议
title: "[Feature] 请输入标题"
labels:
  - "Enhancement"
assignees: Hengxiaopi
body:
- type: textarea
  id: problem-description
  validations:
    required: true
  attributes:
    label: 问题描述
    description: 描述你想要解决的问题或者功能的使用场景
    placeholder: |
      请描述你遇到的问题, 简明扼要的说明该功能的适用场景。
      说明当前应用在没有该功能情况下对你造成了哪些困扰，而有了这项功能后又能为用户创造怎样的价值

- type: textarea
  id: solution-description
  validations:
    required: true
  attributes:
    label: 描述解决方案
    description: 说说对于该问题, 你预期的解决方案是怎样的
    placeholder: |
      尽量清晰地描述你所预期的解决方案，它会以怎样的方式解决你所遇到的问题，这有助于开发者做出符合你预期的更新

- type: textarea
  id: additional-info
  attributes:
    label: 附加信息
    description: 添加一些你认为有必要的备注信息，或者展示一些能表现你思路的草图, 以及你是否愿意提交 Pull Request 来实现这个功能
    render: markdown